# Generated by Django 4.2.10 on 2024-04-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='model_upload/'),
        ),
    ]
