# Generated by Django 4.2.10 on 2024-04-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='drive_type',
            field=models.CharField(choices=[('AWD', 'all-wheel'), ('FWD', 'front-wheel'), ('RWD', 'rear-wheel'), ('4WD', '4-wheel')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Bio-diesel', 'Bio-diesel'), ('Ethanol', 'Ethanol')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default=None, max_length=50),
        ),
    ]
