# Generated by Django 4.2.10 on 2024-04-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_carmodel_drive_type_alter_carmodel_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
