from django.test import TestCase, Client
from django.urls import reverse
from rentals.models import (
    CarType, CarModel, ShopInfo, SocialHandle, ServiceReview,
    )
from rentals.tests.test_models import ModelTestCase


class ViewTestCase(TestCase):
    def setUp(self):
        self.client = Client()
        
        # url
        self.home_url = reverse('home')
    
    
    def test_home_view(self):
        # mock response
        response = self.client.get(self.home_url)
        car_type_data = ModelTestCase.car_type_instance # use instance created in the test.model file
        
        '''
        TEST IF:
            # views exist at the desired location
            # the view uses the correct template
            # the car_type context is in the response generated by the url
            # the type_name of the instance matches that of the actual model
            # 
        '''
        
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'rentals/home.html')
        self.assertTrue('car_type' in response.context)
        self.assertEqual(car_type_data.type_name, 'Mytype')
        